// Generated by CoffeeScript 1.6.2
var express;

express = require('express');

module.exports = {
  load: function(cb) {
    this.getSharedObjectManager().registerObject('httpserver', 'server', express());
    return cb();
  },
  oncall: function(onj, params, cb) {
    var app, e, _base, _base1, _ref, _ref1, _ref2;

    try {
      if ((_ref = params.pluginParameters) == null) {
        params.pluginParameters = {};
      }
      if ((_ref1 = (_base = params.pluginParameters).httpserver) == null) {
        _base.httpserver = {};
      }
      if ((_ref2 = (_base1 = params.pluginParameters.httpserver).port) == null) {
        _base1.port = 80;
      }
      app = this.getSharedObjectManager().getObject('httpserver', 'server').getCurrentContent();
      app.listen(params.pluginParameters.httpserver.port);
      this.getLogger().info("Server listening on port " + params.pluginParameters.httpserver.port);
      return cb();
    } catch (_error) {
      e = _error;
      return cb(e);
    }
  },
  unload: function(cb) {
    return cb();
  }
};
