// Generated by CoffeeScript 1.6.2
var app, connected, express;

express = require('express');

app = express();

connected = false;

module.exports = {
  load: function(cb) {
    this.getSharedObjectManager().registerObject('httpserver', 'server', app);
    return cb();
  },
  oncall: function(onj, params, cb) {
    if (connected === false) {
      app.listen(params.port || 80);
    }
    this.getLogger().info("Server listening on port " + (params.port || 80));
    connected = true;
    return cb();
  },
  unload: function(cb) {
    return cb();
  }
};
