// Generated by CoffeeScript 1.6.2
var app, connected, express;

express = require('express');

app = express();

connected = false;

module.exports = {
  load: function(cb) {
    this.getSharedObjectManager().registerObject('httpserver', 'server', app);
    return cb();
  },
  oncall: function(onj, params, cb) {
    var _base, _base1, _ref, _ref1, _ref2;

    if ((_ref = params.pluginParameters) == null) {
      params.pluginParameters = {};
    }
    if ((_ref1 = (_base = params.pluginParameters).httpserver) == null) {
      _base.httpserver = {};
    }
    if ((_ref2 = (_base1 = params.pluginParameters.httpserver).port) == null) {
      _base1.port = 80;
    }
    if (connected === false) {
      app.listen(params.pluginParameters.httpserver.port);
    }
    this.getLogger().info("Server listening on port " + params.pluginParameters.httpserver.port);
    connected = true;
    return cb();
  },
  unload: function(cb) {
    return cb();
  }
};
